name: Deploy Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop loja || true
            sudo docker rm loja || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/loja-online:v2
            sudo docker run -d -p 80:5000 --name loja ${{ secrets.DOCKERHUB_USERNAME }}/loja-online:v2
